### ISSUE TITLE
`wheelListener` in panzoom.js

### ISSUE THREAD

**Issue by jasonsturges** [mudin/indoorjs#1]
Hi, cool project.

What is `wheelListener` reference in panzoom.js?

https://github.com/mudin/indoorjs/blob/d80237e70247a719afc6eee356610659cc3b5802/src/lib/panzoom.js#L204-L216

Appears to be a missing reference - `wheelListener` is undefined in:

```js
target.removeEventListener('wheel', wheelListener); 
```

**Comment by mudin** [comment]
Hi! Thanks
I will clean this up.
